#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Filename: main.py
Description: Parses waypoints in travel report json input and calculates segments/times and perdiems. Using json file data from /input folder, generated by input.py module

Author: Tatanka5XL
Created: 2025-12-23
Last Modified: 2026-01-10
Version: 0.5
License: Proprietary
"""


from datetime import datetime, timedelta
import json
import os
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment
from openpyxl.worksheet.pagebreak import Break


# =========================
# Helpers
# =========================

def to_isodate(year: str, mmdd: str) -> datetime:
    return datetime.strptime(f"{year}{mmdd}", "%Y%m%d")

def to_isodatetime(year: str, mmdd: str, hhmm: str) -> datetime:
    return datetime.strptime(f"{year}{mmdd}{hhmm}", "%Y%m%d%H%M")

def diff_hours(a: datetime, b: datetime) -> float:
    return (b - a).total_seconds() / 3600

def cz_band(h: float):
    if h < 5:
        return None
    if h < 12:
        return "5_to_12"
    if h < 18:
        return "12_to_18"
    return "over_18"

def foreign_band(h: float):
    if h < 1:
        return None
    if h < 12:
        return "1_to_12"
    if h < 18:
        return "12_to_18"
    return "over_18"

def reduce_meal(base: float, pct: float, meals: int) -> float:
    """Reduce base by pct per meal (cap at 0)."""
    if pct is None:
        return round(base, 2)
    f = 1 - (meals * pct / 100.0)
    return round(max(0.0, base * f), 2)

# =========================
# Build trip days from waypoints (with midnight rules)
# =========================

def build_days(json_data: dict) -> list[dict]:
    year = str(json_data["year"])
    wps_by_day = json_data["waypoints"]

    day_keys = sorted(wps_by_day.keys(), key=int)
    if not day_keys:
        return []

    first_day, last_day = day_keys[0], day_keys[-1]
    days: list[dict] = []

    for mmdd in day_keys:
        wps = wps_by_day.get(mmdd) or []
        if not wps:
            continue

        day_start = to_isodate(year, mmdd)              # 00:00
        day_end = day_start + timedelta(days=1)         # next 00:00

        agg: dict[str, dict] = {}

        def wp_dt(wp):
            return to_isodatetime(year, mmdd, str(wp["time"]))

        # meals
        for wp in wps:
            c = (wp.get("country") or "").strip().upper()
            if not c:
                continue
            agg.setdefault(c, {"country": c, "time_hours": 0.0, "meals": 0})
            agg[c]["meals"] += int(wp.get("meals", 0) or 0)

        # start-of-day extension (middle + last days): 00:00 -> first waypoint
        if mmdd != first_day:
            first_wp = wps[0]
            c = (first_wp.get("country") or "").strip().upper()
            if c:
                agg.setdefault(c, {"country": c, "time_hours": 0.0, "meals": 0})
                h = diff_hours(day_start, wp_dt(first_wp))
                agg[c]["time_hours"] += max(0.0, h)

        # between-waypoints
        for i in range(len(wps) - 1):
            cur, nxt = wps[i], wps[i + 1]
            c = (cur.get("country") or "").strip().upper()
            if not c:
                continue

            a, b = wp_dt(cur), wp_dt(nxt)
            if b < a:
                b += timedelta(days=1)

            h = diff_hours(a, b)
            agg.setdefault(c, {"country": c, "time_hours": 0.0, "meals": 0})
            agg[c]["time_hours"] += max(0.0, h)

        # end-of-day extension (first + middle days): last waypoint -> 24:00
        if mmdd != last_day:
            last_wp = wps[-1]
            c = (last_wp.get("country") or "").strip().upper()
            if c:
                agg.setdefault(c, {"country": c, "time_hours": 0.0, "meals": 0})
                h = diff_hours(wp_dt(last_wp), day_end)
                agg[c]["time_hours"] += max(0.0, h)

        days.append({
            "date": day_start.strftime("%d/%m"),
            "segments": list(agg.values())
        })

    return days

# =========================
# Main: load input + settings
# =========================

default_file = "trep.json"
filename = input(f"Input JSON [{default_file}]: ").strip() or default_file
input_path = os.path.join("..", "input", filename)

if not os.path.isfile(input_path):
    raise FileNotFoundError(f"Input file not found: {input_path}")

with open(input_path, encoding="utf-8") as f:
    data = json.load(f)

settings_path = os.path.join("..", "config", "settings.json")
if not os.path.isfile(settings_path):
    raise FileNotFoundError(f"Settings file not found: {settings_path}")

with open(settings_path, encoding="utf-8") as f:
    settings = json.load(f)

days = build_days(data)

cz_rates = settings["cz"]["per_diems_czk"]
cz_reduce = settings["cz"]["lowering_percents_per_meal"]

foreign_rates = {}
for k, v in settings["foreign"]["per_diems"].items():
    c, cur = k.split("_", 1)
    foreign_rates[c.strip().upper()] = {"rate": float(v), "currency": cur.strip().upper()}

foreign_pct = settings["foreign"]["per_diems_percents"]
foreign_reduce = settings["foreign"]["lowering_percents_per_meal"]

# Exchange rates from input JSON (CNB)
rates_by_currency = {}

for item in data.get("bank_rates", {}).get("currencies", []):
    code = (item.get("code") or "").strip().upper()
    rate = float(item.get("exchange_rate", 0) or 0)
    if code:
        rates_by_currency[code] = rate

if "CZK" not in rates_by_currency: # Safety check only
    rates_by_currency["CZK"] = 1.0

# =========================
# Per diem calculation INTO segments
# =========================

for day in days:
    new_segments = []
    comment_parts = []
    total_perdiem_czk = 0

    # ---------- CZ ----------
    cz_seg = next((s for s in day["segments"] if s.get("country") == "CZ"), None)
    cz_h = float(cz_seg.get("time_hours", 0) or 0) if cz_seg else 0.0
    cz_m = int(cz_seg.get("meals", 0) or 0) if cz_seg else 0

    cz_k = cz_band(cz_h)

    if cz_k is None:
        cz_base = 0.0
        cz_red = None
        cz_amt = 0.0
        cz_band_label = "under_5"
    else:
        cz_base = float(cz_rates[cz_k])
        cz_red = float(cz_reduce[cz_k])
        cz_amt = reduce_meal(cz_base, cz_red, cz_m)
        cz_band_label = cz_k


    new_segments.append({
        "country": "CZ",
        "currency": "CZK",
        "time_hours": round(cz_h, 2),
        "band": cz_band_label,
        "meals": cz_m,
        "base": round(cz_base, 2),
        "reduction_percent": cz_red,
        "amount": round(cz_amt, 2),
    })

    cz_comment = f"CZ {cz_h:.2f}h"
    if cz_red is not None and cz_m > 0:
        cz_comment += f" ({cz_m} meal{'s' if cz_m > 1 else ''}: -{cz_red}%)"
    comment_parts.append(cz_comment)
    
    total_perdiem_czk += cz_amt

    # ---------- FOREIGN ----------
    foreign_segs = [s for s in day["segments"] if s.get("country") != "CZ"]
    if foreign_segs:
        total_h = sum(float(s.get("time_hours", 0) or 0) for s in foreign_segs)
        total_m = sum(int(s.get("meals", 0) or 0) for s in foreign_segs)

        dominant = max(foreign_segs, key=lambda s: float(s.get("time_hours", 0) or 0))
        country = (dominant.get("country") or "").strip().upper()

        band = foreign_band(total_h)

        # defaults so variables always exist
        red = None
        base = 0.0
        amt = 0.0
        cur = foreign_rates.get(country, {}).get("currency")

        # block rule: if CZ >=5h and foreign <5h => 0
        blocked = (cz_h >= 5 and total_h < 5)

        if country and country not in foreign_rates:
            raise KeyError(f"No foreign per diem rate in settings.json for country: {country}")

        if (band is None) or blocked:
            # keep zeros
            pass
        else:
            daily_rate = float(foreign_rates[country]["rate"])
            cur = foreign_rates[country]["currency"]
            pct = float(foreign_pct[band])            # e.g. 100/66/33
            base = round(daily_rate * (pct / 100.0), 2)
            red = float(foreign_reduce.get(band, 0))  # % per meal (can be 0)
            amt = reduce_meal(base, red, total_m)


        new_segments.append({
            "country": country,
            "currency": cur,
            "exch_rate": rates_by_currency[cur],
            "time_hours": round(total_h, 2),
            "band": ("blocked_cz>=5_foreign<5" if blocked else (band or "under_1")),
            "meals": total_m,
            "base": round(base, 2),
            "base_czk": round(base*rates_by_currency[cur], 2),
            "reduction_percent": (red if (red is not None and total_m > 0) else None),
            "amount": round(amt, 2),
            "amount_czk": round(amt * rates_by_currency[cur], 2)
        })

        f_comment = f"{country} {total_h:.2f}h"
        if (red is not None) and total_m > 0 and red != 0:
            f_comment += f" ({total_m} meal{'s' if total_m > 1 else ''}: -{red}%)"
        comment_parts.append(f_comment)
        total_perdiem_czk += (amt * rates_by_currency[cur])

    # ---------- FINAL DAY ----------
    day["segments"] = new_segments
    day["comment"] = " | ".join(comment_parts)
    day["total_perdiem_czk"] = round(total_perdiem_czk, 2)

# =========================
# Output
# =========================

output = {"days": days}

output_path = os.path.join("..", "output", filename.replace(".json", "_days.json"))
os.makedirs(os.path.dirname(output_path), exist_ok=True)

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(output, f, indent=2, ensure_ascii=False)

print(f"\nProcessed data saved to {output_path}")


# ===========================
# Excel sheet generating part
# ===========================

MAX_ROWS = 65
MAX_COLS = 6  # A..F

wb = Workbook()
ws = wb.active
ws.title = "Travelrep CZ"

# --- Print setup (A4 portrait, 1 page) ---
ws.print_area = f"A1:F{MAX_ROWS}"
ws.page_setup.paperSize = ws.PAPERSIZE_A4
ws.page_setup.orientation = ws.ORIENTATION_PORTRAIT
ws.page_setup.fitToWidth = 1
ws.page_setup.fitToHeight = 1
ws.sheet_properties.pageSetUpPr.fitToPage = True

# Margins (inches)
ws.page_margins.left = 0.25
ws.page_margins.right = 0.25
ws.page_margins.top = 0.5
ws.page_margins.bottom = 0.5
ws.page_margins.header = 0.3
ws.page_margins.footer = 0.3

# --- Defaults (font + alignment) applied to A1:F50 only ---
font = Font(name="Helvetica", size=10)
align = Alignment(horizontal="left", vertical="center")

for row in ws.iter_rows(min_row=1, max_row=MAX_ROWS, min_col=1, max_col=MAX_COLS):
    for cell in row:
        cell.font = font
        cell.alignment = align

# Row height
for r in range(1, MAX_ROWS + 1):
    ws.row_dimensions[r].height = 12

# Column widths – fill whole A4 width
ws.column_dimensions["A"].width = 9.5
ws.column_dimensions["B"].width = 37.0
ws.column_dimensions["C"].width = 13.0
ws.column_dimensions["D"].width = 11.0
ws.column_dimensions["E"].width = 11.0
ws.column_dimensions["F"].width = 8.5

# --- Header text ---
bold = Font(name="Helvetica", size=10, bold=True)

ws["A1"] = "Vyúčtování služební cesty"
ws["C1"] = "Profisolv, s.r.o."  
ws["E1"] = "Číslo:"
ws["E2"] = "List:"

ws["A4"] = "Pracovník:"
ws["A5"] = "Účel cesty:"
ws["A6"] = "Prostředek:"
ws["A7"] = "Trasa:"


# Popis trasy
ws["B9"] = "Popis trasy"
ws["B9"].alignment = Alignment(horizontal="center", vertical="center")

headers = ["Bod", "Místo", "Datum", "Čas", "Doba", "Jídla"]
for col_letter, txt in zip("ABCDEF", headers):
    c = ws[f"{col_letter}10"]
    c.value = txt

# Naklady
ws["B30"] = "Náklady"
ws["B30"].alignment = Alignment(horizontal="center", vertical="center")

ws["A31"] = "Stravné"
headers = ["Den", "Popis", "Plné CZ", "Plné zah.", "Celk. den"]
for col_letter, txt in zip("ABDEF", headers):
    c = ws[f"{col_letter}32"]
    c.value = txt
ws["C43"] = "Celkem:"
ws["C44"] = "Kapesné:"
ws["D44"] = "xxxxxxx"
ws["F44"] = "xxxxxxx"


ws["A46"] = "Ubytování"
headers = ["Datum", "Popis", "Doklad č.", "Částka"]
for col_letter, txt in zip("ABEF", headers):
    c = ws[f"{col_letter}47"]
    c.value = txt
ws["E53"] = "Celkem:"

ws["A54"] = "Ostatní"
headers = ["Datum", "Popis", "Doklad č.", "Částka"]
for col_letter, txt in zip("ABEF", headers):
    c = ws[f"{col_letter}55"]
    c.value = txt
ws["E61"] = "Celkem:"

# --- Final counts ---
ws["E63"] = "Záloha:"
ws["A63"] = "Zúčtováno dne:"
ws["A64"] = "Podpis:"
ws["C64"] = "Mezisoučet:"
ws["E64"] = "Náklady:"
ws["E65"] = "K vyplacení:"

# --- Save ---
os.makedirs("../output", exist_ok=True)
out_path = "../output/spam.xlsx"
wb.save(out_path)
print("Excel saved to:", os.path.abspath(out_path))