#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Filename: main.py
Description: Parses waypoints in travel report json input and calculates segments/times and perdiems. Using json file data from /input folder, generated by input.py module

Author: Tatanka5XL
Created: 2025-12-23
Last Modified: 2026-01-29
Version: 0.5
License: Proprietary
"""


from datetime import datetime, timedelta
import json
import os
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, Border, Side


# =========================
# Helpers
# =========================

def to_isodate(year: str, mmdd: str) -> datetime:
    return datetime.strptime(f"{year}{mmdd}", "%Y%m%d")

def to_isodatetime(year: str, mmdd: str, hhmm: str) -> datetime:
    return datetime.strptime(f"{year}{mmdd}{hhmm}", "%Y%m%d%H%M")

def diff_hours(a: datetime, b: datetime) -> float:
    return (b - a).total_seconds() / 3600

def cz_band(h: float):
    if h < 5:
        return None
    if h < 12:
        return "5_to_12"
    if h < 18:
        return "12_to_18"
    return "over_18"

def foreign_band(h: float):
    if h < 1:
        return None
    if h < 12:
        return "1_to_12"
    if h < 18:
        return "12_to_18"
    return "over_18"

def reduce_meal(base: float, pct: float, meals: int) -> float:
    """Reduce base by pct per meal (cap at 0)."""
    if pct is None:
        return round(base, 2)
    f = 1 - (meals * pct / 100.0)
    return round(max(0.0, base * f), 2)

def to_mmdd(date_str: str) -> str:
    # input is usually "DD/MM" -> output "MM/DD"
    if not date_str or "/" not in date_str:
        return date_str
    dd, mm = date_str.split("/", 1)
    return f"{dd}/{mm}"

def mmdd_to_ddmm(mmdd: str) -> str:
    """
    Convert 'MMDD' -> 'DD/MM'
    Example: '0112' -> '12/01'
    """
    if not mmdd or len(mmdd) != 4 or not mmdd.isdigit():
        return mmdd

    mm = mmdd[:2]
    dd = mmdd[2:]
    return f"{dd}/{mm}"

# =========================
# Build trip days from waypoints (with midnight rules)
# =========================

def build_days(json_data: dict) -> list[dict]:
    year = str(json_data["year"])
    wps_by_day = json_data["waypoints"]

    day_keys = sorted(wps_by_day.keys(), key=int)
    if not day_keys:
        return []

    first_day, last_day = day_keys[0], day_keys[-1]
    days: list[dict] = []

    for mmdd in day_keys:
        wps = wps_by_day.get(mmdd) or []
        if not wps:
            continue

        day_start = to_isodate(year, mmdd)              # 00:00
        day_end = day_start + timedelta(days=1)         # next 00:00

        agg: dict[str, dict] = {}

        def wp_dt(wp):
            return to_isodatetime(year, mmdd, str(wp["time"]))

        # meals
        for wp in wps:
            c = (wp.get("country") or "").strip().upper()
            if not c:
                continue
            agg.setdefault(c, {"country": c, "time_hours": 0.0, "meals": 0})
            agg[c]["meals"] += int(wp.get("meals", 0) or 0)

        # start-of-day extension (middle + last days): 00:00 -> first waypoint
        if mmdd != first_day:
            first_wp = wps[0]
            c = (first_wp.get("country") or "").strip().upper()
            if c:
                agg.setdefault(c, {"country": c, "time_hours": 0.0, "meals": 0})
                h = diff_hours(day_start, wp_dt(first_wp))
                agg[c]["time_hours"] += max(0.0, h)

        # between-waypoints
        for i in range(len(wps) - 1):
            cur, nxt = wps[i], wps[i + 1]
            c = (cur.get("country") or "").strip().upper()
            if not c:
                continue

            a, b = wp_dt(cur), wp_dt(nxt)
            if b < a:
                b += timedelta(days=1)

            h = diff_hours(a, b)
            agg.setdefault(c, {"country": c, "time_hours": 0.0, "meals": 0})
            agg[c]["time_hours"] += max(0.0, h)

        # end-of-day extension (first + middle days): last waypoint -> 24:00
        if mmdd != last_day:
            last_wp = wps[-1]
            c = (last_wp.get("country") or "").strip().upper()
            if c:
                agg.setdefault(c, {"country": c, "time_hours": 0.0, "meals": 0})
                h = diff_hours(wp_dt(last_wp), day_end)
                agg[c]["time_hours"] += max(0.0, h)

        days.append({
            "date": day_start.strftime("%d/%m"),
            "segments": list(agg.values())
        })

    return days

# =========================
# Main: load input + settings
# =========================

default_file = "0101_itfr.json"
filename = input(f"Input JSON [{default_file}]: ").strip() or default_file
input_path = os.path.join("..", "input", filename)

if not os.path.isfile(input_path):
    raise FileNotFoundError(f"Input file not found: {input_path}")

with open(input_path, encoding="utf-8") as f:
    data = json.load(f)

settings_path = os.path.join("..", "config", "settings.json")
if not os.path.isfile(settings_path):
    raise FileNotFoundError(f"Settings file not found: {settings_path}")

with open(settings_path, encoding="utf-8") as f:
    settings = json.load(f)

days = build_days(data)

cz_rates = settings["cz"]["per_diems_czk"]
cz_reduce = settings["cz"]["lowering_percents_per_meal"]

foreign_rates = {}
for k, v in settings["foreign"]["per_diems"].items():
    c, cur = k.split("_", 1)
    foreign_rates[c.strip().upper()] = {"rate": float(v), "currency": cur.strip().upper()}

foreign_pct = settings["foreign"]["per_diems_percents"]
foreign_reduce = settings["foreign"]["lowering_percents_per_meal"]

# Exchange rates from input JSON (CNB)
rates_by_currency = {}

for item in data.get("bank_rates", {}).get("currencies", []):
    code = (item.get("code") or "").strip().upper()
    rate = float(item.get("exchange_rate", 0) or 0)
    if code:
        rates_by_currency[code] = rate

if "CZK" not in rates_by_currency: # Safety check only
    rates_by_currency["CZK"] = 1.0

# =========================
# Per diem calculation INTO segments
# =========================

total_perdiems_cz = 0
total_perdiems_foreign_base = 0
total_perdiems_foreign_reduced = 0
total_accomodation = 0
total_others = 0

for day in days:
    new_segments = []
    comment_parts = []
    total_perdiem_czk = 0

    # ---------- CZ ----------
    cz_seg = next((s for s in day["segments"] if s.get("country") == "CZ"), None)

    cz_h = float(cz_seg.get("time_hours", 0) or 0) if cz_seg else 0.0
    cz_m = int(cz_seg.get("meals", 0) or 0) if cz_seg else 0

    # Only create CZ output segment if there is ANY time in CZ
    if cz_h > 0:
        cz_k = cz_band(cz_h)

        if cz_k is None:
            cz_base = 0.0
            cz_red = None
            cz_amt = 0.0
            cz_band_label = "under_5"
        else:
            cz_base = float(cz_rates[cz_k])
            cz_red = float(cz_reduce[cz_k])
            cz_amt = reduce_meal(cz_base, cz_red, cz_m)
            cz_band_label = cz_k

        new_segments.append({
            "country": "CZ",
            "currency": "CZK",
            "time_hours": round(cz_h, 2),
            "band": cz_band_label,
            "meals": cz_m,
            "base": round(cz_base, 2),
            "reduction_percent": cz_red,
            "amount": round(cz_amt, 2),
        })

        cz_comment = f"CZ {cz_h:.2f}h"
        if cz_red is not None and cz_m > 0:
            cz_comment += f" ({cz_m} jídl{'a' if cz_m > 1 else 'o'}: -{cz_red}%)"
        comment_parts.append(cz_comment)

        total_perdiem_czk += cz_amt
        total_perdiems_cz += total_perdiem_czk

    # ---------- FOREIGN ----------
    foreign_segs = [s for s in day["segments"] if s.get("country") != "CZ"]
    
    if foreign_segs:
        total_h = sum(float(s.get("time_hours", 0) or 0) for s in foreign_segs)
        total_m = sum(int(s.get("meals", 0) or 0) for s in foreign_segs)

        dominant = max(foreign_segs, key=lambda s: float(s.get("time_hours", 0) or 0))
        dominant_country = (dominant.get("country") or "").strip().upper()

        band = foreign_band(total_h)

        # defaults so variables always exist
        red = None
        base = 0.0
        amt = 0.0
        dominant_cur = foreign_rates.get(dominant_country, {}).get("currency")

        # block rule: if CZ >=5h and foreign <5h => 0
        blocked = (cz_h >= 5 and total_h < 5)

        if dominant_country not in foreign_rates:
            raise KeyError(f"No foreign per diem rate in settings.json for country: {dominant_country}")

        if (band is None) or blocked:
            # keep zeros
            pass
        else:
            daily_rate = float(foreign_rates[dominant_country]["rate"])
            dominant_cur = foreign_rates[dominant_country]["currency"]
            pct = float(foreign_pct[band])            # e.g. 100/66/33
            base = round(daily_rate * (pct / 100.0), 2)
            red = float(foreign_reduce.get(band, 0))  # % per meal (can be 0)
            amt = reduce_meal(base, red, total_m)

        for seg in foreign_segs:
            if seg["country"] == dominant_country:
                new_segments.append({
                    "country": seg["country"],
                    "currency": dominant_cur,
                    "exch_rate": rates_by_currency[dominant_cur],
                    "time_hours": round(seg["time_hours"], 2),
                    "band": ("blocked_cz>=5_foreign<5" if blocked else (band or "under_1")),
                    "meals": total_m,
                    "base": round(base, 2),
                    "base_czk": round(base*rates_by_currency[dominant_cur], 2),
                    "reduction_percent": (red if (red is not None and total_m > 0) else None),
                    "amount": round(amt, 2),
                    "amount_czk": round(amt * rates_by_currency[dominant_cur], 2)
                })
                total_perdiems_foreign_base += base * rates_by_currency[dominant_cur]
                total_perdiems_foreign_reduced += amt * rates_by_currency[dominant_cur]
            else:
                country = seg["country"]
                cur = foreign_rates.get(country, {}).get("currency")
                new_segments.append({
                    "country": country,
                    "currency": cur,
                    "exch_rate": None,
                    "time_hours": round(seg["time_hours"],2),
                    "band": None,
                    "meals": None,
                    "base": None,
                    "base_czk": 0,
                    "reduction_percent": 0,
                    "amount": 0,
                    "amount_czk": 0
                })

        f_comment = f"Hlav. země: {dominant_country} - celk. {total_h:.2f}h"
        if (red is not None) and total_m > 0 and red != 0:
            f_comment += f" ({total_m} jídl{'a' if total_m > 1 else 'o'}: -{red}%)"
        comment_parts.append(f_comment)
        total_perdiem_czk += (amt * rates_by_currency[cur])

    # ---------- FINAL DAY ----------
    day["segments"] = new_segments
    day["comment"] = " | ".join(comment_parts)
    day["total_perdiem_czk"] = round(total_perdiem_czk, 2)




total_pocket_money = total_perdiems_foreign_base * 0.4
total_to_be_paid = total_perdiems_cz + total_perdiems_foreign_reduced + total_pocket_money + total_accomodation + total_others

totals = {
    "total_perdiems_cz": round(total_perdiems_cz, 2),
    "total_perdiems_foreign": round(total_perdiems_foreign_reduced, 2),
    "total_pocket_money": round(total_pocket_money, 2),
    "total_to_be_paid": round(total_to_be_paid, 2)
    }


# =========================
# Output
# =========================

output = {
    "days": days,
    "totals": totals
    }

output_path = os.path.join("..", "output", filename.replace(".json", "_out.json"))
os.makedirs(os.path.dirname(output_path), exist_ok=True)

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(output, f, indent=2, ensure_ascii=False)

print(f"\nProcessed data saved to {output_path}")


# ===========================
# Excel sheet generating part
# ===========================

MAX_ROWS = 65
MAX_COLS = 6  # A..F

wb = Workbook()
ws = wb.active
ws.title = "Travelrep CZ"

# --- Print setup (A4 portrait, 1 page) ---
ws.print_area = f"A1:F{MAX_ROWS}"
ws.page_setup.paperSize = ws.PAPERSIZE_A4
ws.page_setup.orientation = ws.ORIENTATION_PORTRAIT
ws.page_setup.fitToWidth = 1
ws.page_setup.fitToHeight = 1
ws.sheet_properties.pageSetUpPr.fitToPage = True

# Margins (inches)
ws.page_margins.left = 0.25
ws.page_margins.right = 0.25
ws.page_margins.top = 0.5
ws.page_margins.bottom = 0.5
ws.page_margins.header = 0.3
ws.page_margins.footer = 0.3

# --- Defaults (font + alignment) applied to A1:F50 only ---
font = Font(name="Helvetica", size=10)
align = Alignment(horizontal="left", vertical="center")

for row in ws.iter_rows(min_row=1, max_row=MAX_ROWS, min_col=1, max_col=MAX_COLS):
    for cell in row:
        cell.font = font
        cell.alignment = align

# Row height
for r in range(1, MAX_ROWS + 1):
    ws.row_dimensions[r].height = 15

# Column widths – fill whole A4 width
ws.column_dimensions["A"].width = 9.5
ws.column_dimensions["B"].width = 37.0
ws.column_dimensions["C"].width = 13.0
ws.column_dimensions["D"].width = 11.0
ws.column_dimensions["E"].width = 11.0
ws.column_dimensions["F"].width = 8.5

# Cell borders - top and bottom, for tables only
thin = Side(style="thin")


# --- Header text ---
bold = Font(name="Helvetica", size=10, bold=True)
underline = Font(name="Helvetica", size=10, underline="single")

ws["A1"] = "Vyúčtování služební cesty"; ws["A1"].font = bold
ws["C1"] = "Profisolv, s.r.o."
ws["C2"] = data["year"]
ws["E1"] = "Číslo:"; ws["E1"].font = bold
ws["F1"] = data["report_id"]
ws["E2"] = "List:"; ws["E2"].font = bold
ws["F2"] = "1 z 1"
ws["E3"] = "Kurzy ČNB:"; ws["E3"].font = bold
ws["F3"] = mmdd_to_ddmm(data["bank_rates"]["effective_date"])
ws["E4"] = "Měna:"; ws["E4"].font = bold
ws["F4"] = "CZK"

ws["A4"] = "Pracovník:"
ws["B4"] = data["employee"]["name"]
ws["A5"] = "Účel cesty:"
ws["B5"] = data["trip_info"]["trip_description"]
ws["A6"] = "Prostředek:"
ws["B6"] = data["trip_info"]["transport"]["mode"]
ws["A7"] = "Trasa:"
ws["B7"] = data["trip_info"]["target_locations"]


# Popis trasy
# Ohraniceni bunek
for row in range(11, 29):          # rows 11..28
    for col in range(1, 7):        # columns A..F

        border = Border(
            top=thin,
            bottom=thin,
            left=thin if col == 1 else None,   # column A
            right=thin if col == 6 else None,  # column F
        )

        ws.cell(row=row, column=col).border = border

ws["B9"] = "Popis trasy"; ws["B9"].font = bold
ws["B9"].alignment = Alignment(horizontal="center", vertical="center")

headers = ["Země", "Místo", "Typ", "Datum", "Čas", "Jídla"]
for col_letter, txt in zip("ABCDEF", headers):
    c = ws[f"{col_letter}10"]
    c.value = txt
    c.font = bold
    c.alignment = Alignment(vertical = "center")


# Naklady
ws["B30"] = "Náklady"
ws["B30"].alignment = Alignment(horizontal="center", vertical="center")
ws["B30"].font = bold

# Ohraniceni bunek stravne
for row in range(33, 43):          # rows 33..42
    for col in range(1, 7):        # columns A..F

        border = Border(
            top=thin,
            bottom=thin,
            left=thin if col == 1 else None,   # column A
            right=thin if col == 6 else None,  # column F
        )

        ws.cell(row=row, column=col).border = border

ws["B31"] = "Stravné"; ws["B31"].font = bold
headers = ["Den", "Popis", "Plné CZ", "Plné zah.", "Celk. den"]
for col_letter, txt in zip("ABDEF", headers):
    c = ws[f"{col_letter}32"]
    c.value = txt
    c.font = bold
    c.alignment = Alignment(vertical = "center")

ws["C43"] = "Celkem:"
ws["C44"] = "Kapesné:"
ws["D44"] = "xxxxxxx"
ws["F44"] = "xxxxxxx"

# Ohraniceni bunek ubytovani
for row in range(48, 53):          # rows 48..52
    for col in range(1, 7):        # columns A..F

        border = Border(
            top=thin,
            bottom=thin,
            left=thin if col == 1 else None,   # column A
            right=thin if col == 6 else None,  # column F
        )

        ws.cell(row=row, column=col).border = border

ws["B46"] = "Ubytování"; ws["B46"].font = bold
headers = ["Datum", "Popis", "Doklad č.", "Částka"]
for col_letter, txt in zip("ABEF", headers):
    c = ws[f"{col_letter}47"]
    c.value = txt
    c.font = bold
    c.alignment = Alignment(vertical = "center")

ws["E53"] = "Celkem:"

# Ohraniceni bunek ostatni
for row in range(56, 61):          # rows 56..60
    for col in range(1, 7):        # columns A..F

        border = Border(
            top=thin,
            bottom=thin,
            left=thin if col == 1 else None,   # column A
            right=thin if col == 6 else None,  # column F
        )

        ws.cell(row=row, column=col).border = border

ws["B54"] = "Ostatní"; ws["B54"].font = bold
headers = ["Datum", "Popis", "Doklad č.", "Částka"]
for col_letter, txt in zip("ABEF", headers):
    c = ws[f"{col_letter}55"]
    c.value = txt
    c.font = bold
    c.alignment = Alignment(vertical = "center")

ws["E61"] = "Celkem:"

# --- Final counts ---
ws["E63"] = "Záloha:"
ws["A63"] = "Zúčt. dne:"
ws["A64"] = "Podpis:"
ws["C64"] = "Mezisoučet:"
ws["E64"] = "Náklady:"
ws["E65"] = "K vyplacení:"; ws["E65"].font = bold


# --- Filling in waypoints ---
def fill_waypoints_into_route(ws, waypoints: dict, start_row=11):
    """
    Writes waypoints into Excel worksheet row-by-row,
    starting at A{start_row} with column order:
    Country | Place | Type | Date | Time | Meals
    """

    row = start_row  # A11

    for mmdd in sorted(waypoints.keys()):
        day_points = waypoints[mmdd]
        date_str = f"{mmdd[2:]}/{mmdd[:2]}"  # DD/MM

        # meals per country (for Arrival row)
        meals_by_country = {}
        for wp in day_points:
            c = wp["country"]
            meals_by_country[c] = meals_by_country.get(c, 0) + int(wp.get("meals", 0))

        def fmt_time(t):
            return f"{t[:2]}:{t[2:]}"

        # ---------- Departure ----------
        first = day_points[0]
        ws.cell(row=row, column=1, value=first["country"])                     # Country
        ws.cell(row=row, column=2, value=first["place"])  # Place
        ws.cell(row=row, column=3, value="Odjezd")                          # Type
        ws.cell(row=row, column=4, value=date_str)                             # Date
        ws.cell(row=row, column=5, value=fmt_time(first["time"]))              # Time
        ws.cell(row=row, column=6, value="")                                   # Meals
        row += 1

        # ---------- Border crossings ----------
        prev_country = first["country"]

        for wp in day_points[1:-1]:
            if wp["country"] != prev_country:
                ws.cell(row=row, column=1, value=wp["country"])
                ws.cell(row=row, column=2, value=wp["place"])
                ws.cell(row=row, column=3, value="Přechod hr.")
                ws.cell(row=row, column=4, value=date_str)
                ws.cell(row=row, column=5, value=fmt_time(wp["time"]))
                ws.cell(row=row, column=6, value="")
                row += 1
                prev_country = wp["country"]

        # ---------- Arrival ----------
        last = day_points[-1]
        meals_text = ", ".join(
            f"{c}-{m}" for c, m in meals_by_country.items() if m > 0
        )

        ws.cell(row=row, column=1, value=last["country"])
        ws.cell(row=row, column=2, value=last["place"])
        ws.cell(row=row, column=3, value="Příjezd")
        ws.cell(row=row, column=4, value=date_str)
        ws.cell(row=row, column=5, value=fmt_time(last["time"]))
        ws.cell(row=row, column=6, value=meals_text)
        row += 1

# --- Fill in perdiems ---
def fill_days_into_perdiems(ws, days: list[dict], start_row: int = 33, pocket_percent: float = 40.0):
    """
    Writes per-diem summary rows starting at A{start_row} (default A33).

    Per row:
      A = Day (MM/DD)
      B = Description (day["comment"])
      D = Full CZ per-diem (base, no meal reduction) [CZK]
      E = Full FOREIGN per-diem (base_czk, no meal reduction) [CZK]
      F = Reduced total (CZ reduced + foreign reduced) [CZK]

    Totals:
      D43 = total full CZ (trip)
      E43 = total full FOREIGN (trip)
      F43 = total reduced total (trip)
      E44 = total pocket money (trip) in CZK = pocket_percent% of FOREIGN full bases (CZK)
    """



    def seg_is_foreign(seg: dict) -> bool:
        c = (seg.get("currency") or "").upper()
        return c and c != "CZK"

    row = start_row

    total_full_perdiem_cz = 0.0
    total_full_perdiem_foreign = 0.0
    total_perdiem_reduced = 0.0
    total_pocket = 0.0

    for day in days:
        date_out = to_mmdd(day.get("date", ""))
        comment = day.get("comment", "")

        # Find CZ segment (if present)
        cz_seg = next((s for s in day.get("segments", []) if (s.get("currency") or "").upper() == "CZK"), None)
        cz_full = float(cz_seg.get("base", 0) or 0) if cz_seg else 0.0
        cz_reduced = float(cz_seg.get("amount", 0) or 0) if cz_seg else 0.0

        # Sum foreign (if multiple foreign segments exist)
        foreign_segs = [s for s in day.get("segments", []) if seg_is_foreign(s)]
        foreign_full_czk = sum(float(s.get("base_czk", 0) or 0) for s in foreign_segs)
        foreign_reduced_czk = sum(float(s.get("amount_czk", 0) or 0) for s in foreign_segs)

        reduced_total_czk = cz_reduced + foreign_reduced_czk

        # Pocket money = % of FOREIGN full base in CZK
        pocket_czk = round(foreign_full_czk * (float(pocket_percent) / 100.0), 2)

        # Write row
        ws.cell(row=row, column=1, value=date_out)                      # A
        ws.cell(row=row, column=2, value=comment)                       # B
        # column C intentionally blank
        ws.cell(row=row, column=4, value=round(cz_full, 2))              # D
        ws.cell(row=row, column=5, value=round(foreign_full_czk, 2))     # E
        ws.cell(row=row, column=6, value=round(reduced_total_czk, 2))    # F

        # Accumulate totals
        total_full_perdiem_cz += cz_full
        total_full_perdiem_foreign += foreign_full_czk
        total_perdiem_reduced += reduced_total_czk
        total_pocket += pocket_czk

        row += 1

    # Perdiem totals into fixed cells
    ws["D43"] = round(total_full_perdiem_cz, 2)
    ws["E43"] = round(total_full_perdiem_foreign, 2)
    ws["F43"] = round(total_perdiem_reduced, 2); ws["F43"].font = bold
    ws["E44"] = round(total_pocket, 2); ws["E44"].font = bold

#TODO --- Fill in Accomodation ---

#TODO --- Fill in Others ----

# --- Fill in trip totals ----
last_mmdd = sorted(data["waypoints"].keys())[-1]
last_day_formatted = f"{last_mmdd[:2]}/{last_mmdd[2:]}"
ws["B63"] = last_day_formatted

subtotal = 0 #TODO add multi-page funcionality for large trips!
ws["D64"] = subtotal

cash_advance = 0  #TODO Add to data input!
ws["F63"] = cash_advance

total_trip_costs = subtotal +  totals["total_to_be_paid"]
ws["F64"] = total_trip_costs

total_to_pay = total_trip_costs - cash_advance 
ws["F65"] = total_to_pay; ws["F65"].font = bold

# --- Save ---
out_path = os.path.expanduser(
    f"~/Documents/profi/mzda/travel_reports/{data['report_id']}.xlsx"
)

fill_waypoints_into_route(ws, data["waypoints"], start_row=11)

fill_days_into_perdiems(
    ws=ws,
    days=days,
    start_row=33,        # A33
    pocket_percent=40.0  # from settings.json
)

wb.save(out_path)
print("Excel saved to:", os.path.abspath(out_path))